resources:
  - url: http://127.0.0.1:5000/tam-card.js
    type: module
views:
  - cards:
      - type: custom:tam-card
        stop: PABLO PICASSO
        line: '3'
        direction_id: 1
        destination: LATTES CENTRE
